version: '1.0'
name: master-pipeline
displayName: MasterPipeline
triggers:
  trigger: auto
  push:
    branches:
      include:
        - master
stages:
  - name: compile
    displayName: 编译
    strategy: naturally
    trigger: auto
    steps:
      - step: build@gcc
        name: build_gcc
        displayName: GCC 构建
        gccVersion: '15.2'
        commands:
          - '# 安装依赖'
          - apt update && apt upgrade
          - apt install gcc g++ gdb cmake
          - apt install libc6 libstdc++6 libqt6core6 libqt6gui6 libqt6widgets libqt6svg6 qt6-qpa-plugins qt6-image-formats-plugins
          - apt install qt6-base-dev libqt6svg6-dev
          - ''
          - '# 新建build目录，切换到build目录'
          - 'mkdir build && cd build '
          - '# 生成CMake'
          - cmake ..
          - '# 编译'
          - cmake --build . --config Release
          - '# 安装'
          - cmake --install .
        artifacts:
          - name: BUILD_ARTIFACT
            path:
              - ./Install/bin
        caches: []
        notify: []
        strategy:
          retry: '0'
      - step: publish@general_artifacts
        name: publish_general_artifacts
        displayName: 上传制品
        dependArtifact: BUILD_ARTIFACT
        artifactName: output
        dependsOn: build_gcc
